# Generated by Django 3.0.8 on 2020-07-07 20:23

from django.db import migrations, models
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treebeardmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treebeardns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True)),
                ('rgt', models.PositiveIntegerField(db_index=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treebeardal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sib_order', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='exampleapp.Treebeardal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mptt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Mptt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mptt', treewidget.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Mptt')),
                ('mptt_many', treewidget.fields.TreeManyToManyField(related_name='example_many', to='exampleapp.Mptt')),
                ('treebeardal', treewidget.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Treebeardal')),
                ('treebeardal_many', treewidget.fields.TreeManyToManyField(related_name='example_many', to='exampleapp.Treebeardal')),
                ('treebeardmp', treewidget.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Treebeardmp')),
                ('treebeardmp_many', treewidget.fields.TreeManyToManyField(related_name='example_many', to='exampleapp.Treebeardmp')),
                ('treebeardns', treewidget.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Treebeardns')),
                ('treebeardns_many', treewidget.fields.TreeManyToManyField(related_name='example_many', to='exampleapp.Treebeardns')),
            ],
        ),
    ]
