# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Category')),
            ],
        ),
    ]
