# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0003_bla'),
    ]

    operations = [
        migrations.CreateModel(
            name='AL_TestNodeSorted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.IntegerField()),
                ('val2', models.IntegerField()),
                ('desc', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='exampleapp.AL_TestNodeSorted')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bla',
            name='al',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleapp.AL_TestNodeSorted'),
        ),
    ]
